version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fullstock-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fullstock
      POSTGRES_USER: fullstock
      POSTGRES_PASSWORD: fullstock123
    ports:
      - "5432:5432"
    volumes:
      - fullstock_data:/var/lib/postgresql/data

volumes:
  fullstock_data:
